---
title: Creativity & Code
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
email: me@sushkelly.co.uk
description: 'An Interactive Designer based in Birmingham and working at Imaginate
  Creative Ltd in Leamington Spa. I love designing and developing for screen, getting
  out into the hills and getting muddy.  I have a weakness for anthing Orange and
  tech gadgets.

'
baseurl: ''
url: http://www.sushkelly.co.uk
twitter_username: maxray
github_username: maxray
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
gems:
- jekyll-archives
jekyll-archives:
  enabled:
  - all
  layout: archive
  permalinks:
    year: "/archive/:year/"
    month: "/archive/:year/:month/"
    day: "/archive/:year/:month/:day/"
    tag: "/archive/tag/:name/"
    category: "/archive/category/:name/"
ftp_host: www.sushkelly.co.uk
ftp_dir: "/public_html/"
ftp_passive: true
ftp_port: 21
ftp_username: maxray
ftp_password: JHByMW5nZjFlbEQ=
ftp_secure: false
