---
title: Creativity & Code
timezone: UTC
collections:
  case-studies:
    title: Case Studies
    output: true
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
  weeknotes:
    title: Week Notes
    output: true
defaults:
- scope:
    path: ''
    type: weeknotes
  values:
    layout: weeknote
    weekvibe: 
email: sush@creativityandcode.co.uk
description: 'An Interactive Designer/Developer based in Birmingham. Love anything
  on two wheels and have a weakness for anything Orange.

'
baseurl: 
excerpt_separator: "<!--more-->"
url: https://www.sushkelly.co.uk
twitter_username: maxray
github_username: maxray
markdown: kramdown
sass:
  sass_dir: _sass
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-archives
jekyll-archives:
  enabled:
  - all
  layout: archive
  permalinks:
    year: "/archive/:year/"
    month: "/archive/:year/:month/"
    day: "/archive/:year/:month/:day/"
    tag: "/archive/tag/:name/"
    category: "/archive/category/:name/"
