---
title: Creativity & Code
timezone: UTC
collections:
  case-studies:
    title: Case Studies
    output: true
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
email: sush@creativityandcode.co.uk
description: 'An Interactive Designer based in Birmingham. I love designing and developing
  for screen, getting out into the hills and getting muddy.  I have a weakness for
  anything Orange and tech gadgets.

'
baseurl: 
excerpt_separator: "<!--more-->"
url: http://www.sushkelly.co.uk
twitter_username: maxray
github_username: maxray
markdown: kramdown
sass:
  sass_dir: _sass
plugins:
- jekyll-archives
jekyll-archives:
  enabled:
  - all
  layout: archive
  permalinks:
    year: "/archive/:year/"
    month: "/archive/:year/:month/"
    day: "/archive/:year/:month/:day/"
    tag: "/archive/tag/:name/"
    category: "/archive/category/:name/"
ftp_host: www.sushkelly.co.uk
ftp_dir: "/public_html/"
ftp_passive: true
ftp_port: 21
ftp_username: maxray
ftp_password: JHByMW5nZjFlbEQ=
ftp_secure: false
